platform :ios, '8.0'
target 'rectNavtive' do 
pod 'React', :path => './node_modules/react-native', :subspecs => [ 
'Core',
'RCTNetwork',
'RCTText',
'RCTWebSocket',
'RCTImage',
]
pod 'Yoga', :path => './node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

end
